### ISSUE TITLE
Error submitting lift for old W69+ youth category

### ISSUE THREAD

**Issue by ditorelo** [WeightliftingNZ/lifter-api#18]
**Describe the bug**
Adding new lifts, found a 400 when adding a record for a the old "W69+" youth category

**To Reproduce**
```
400 Client Error: Bad Request for url: https://api.lifter.shivan.xyz/v1/competitions/o45jgLy/lifts
{'lottery_number': 44, 'athlete_id': 'YblBVr9', 'competition_id': 'o45jgLy', 'bodyweight': 71.55, 'weight_category': 'W69+', 'team': 'SOW', 'session_number': 2.0, 'snatch_first': 'LIFT', 'snatch_first_weight': 35.0, 'snatch_second': 'LIFT', 'snatch_second_weight': 36.0, 'snatch_third': 'LIFT', 'snatch_third_weight': 38.0, 'cnj_first': 'LIFT', 'cnj_first_weight': 45.0, 'cnj_second': 'LIFT', 'cnj_second_weight': 47.0, 'cnj_third': 'LIFT', 'cnj_third_weight': 49.0}
```

Competion:
https://lifter.shivan.xyz/competitions/o45jgLy

**Comment by ditorelo** [comment]
Another one - is W38 a youth category as well?

400 Client Error: Bad Request for url: https://api.lifter.shivan.xyz/v1/competitions/V21v3pd/lifts
```{
  "lottery_number": 5,
  "athlete_id": "YblBVr9",
  "competition_id": "V21v3pd",
  "bodyweight": 69.7,
  "weight_category": "W38",
  "team": "SOW",
  "session_number": "1",
  "snatch_first": "LIFT",
  "snatch_first_weight": 35.0,
  "snatch_second": "NOLIFT",
  "snatch_second_weight": 38.0,
  "snatch_third": "NOLIFT",
  "snatch_third_weight": 40.0,
  "cnj_first": "LIFT",
  "cnj_first_weight": 40.0,
  "cnj_second": "LIFT",
  "cnj_second_weight": 42.0,
  "cnj_third": "LIFT",
  "cnj_third_weight": 43.0
}```

**Comment by ditorelo** [comment]
Andddd one more, M50

```
{
  "lottery_number": 1,
  "athlete_id": "g8xZq3W",
  "competition_id": "3qpNBpB",
  "bodyweight": 43.2,
  "weight_category": "M50",
  "team": "NOW",
  "session_number": 5.0,
  "snatch_first": "NOLIFT",
  "snatch_first_weight": 50.0,
  "snatch_second": "LIFT",
  "snatch_second_weight": 50.0,
  "snatch_third": "LIFT",
  "snatch_third_weight": 53.0,
  "cnj_first": "LIFT",
  "cnj_first_weight": 61.0,
  "cnj_second": "NOLIFT",
  "cnj_second_weight": 65.0,
  "cnj_third": "LIFT",
  "cnj_third_weight": 65.0
}
```

**Comment by shivan-s** [comment]
Haha, what are these weight classes?

**Comment by ditorelo** [comment]
Looks like we're missing the old W48 too 

400 Client Error: Bad Request for url: https://api.lifter.shivan.xyz/v1/competitions/JbLbJL8/lifts
```
{
  "lottery_number": 1,
  "athlete_id": "YbOjN8k",
  "competition_id": "JbLbJL8",
  "bodyweight": 52.6,
  "weight_category": "F48",
  "team": "SOW",
  "session_number": "1",
  "snatch_first": "LIFT",
  "snatch_first_weight": 26.0,
  "snatch_second": "LIFT",
  "snatch_second_weight": 30.0,
  "snatch_third": "NOLIFT",
  "snatch_third_weight": 31.0,
  "cnj_first": "LIFT",
  "cnj_first_weight": 32.0,
  "cnj_second": "LIFT",
  "cnj_second_weight": 36.0,
  "cnj_third": "NOLIFT",
  "cnj_third_weight": 40.0
}
```

**Comment by ditorelo** [comment]
Just hold mate - let me get my ducks in a roll. 
Best info I have right now is this

<img width="574" alt="image" src="https://user-images.githubusercontent.com/642102/189553496-5104c5bf-1eeb-4e20-bef5-345b47f24498.png">

**Comment by ditorelo** [comment]
So, definitely missing for old weight categories:
- W48
- Possibly W44 (youth) (haven't encountered yet though)
- M50 (youth)
- W69+ (usually youth has one less category than senior)

**Comment by ditorelo** [comment]
Categories that need adding:

Current:
- Youth Male 49
- Youth Female 40

Legacy:
- Youth Male 50, 94, 94+
- Youth Female 44, 69, 69+

**Comment by ditorelo** [comment]
current_male = [55,61,67,73,81,89,96,102,109, 109+]
        current_female = [45,49,55,59,64,71,76,81,87, 87+]

        legacy_male = [56, 62, 69, 77, 85, 94,105, 105+]
        legacy_female = [48,53,58,63,69,75, 105+] 

        current_youth_male = [49, 55,61,67,73,81,89,96,102,102+]
        current_youth_female = [40, 45,49,55,59,64,71,76,81,87, 87+]

        legacy_youth_male = [50, 56, 62, 69, 77, 85, 94, 94+]
        legacy_youth_female = [44, 48,53,58,63,69,75, 75+]

**Comment by shivan-s** [comment]
@ditorelo has this issue been resolved?
