### ISSUE TITLE
Better error messages for data validation

### ISSUE THREAD

**Issue by ditorelo** [WeightliftingNZ/lifter-api#19]
**Describe the bug**
Got a 500 returned when trying to add a lift.

Turns out that whole spreadsheet didn't have session numbers. When adding ,I was setting them to zero. 
Two other records were recorded, and I got  500 from the API. On a hunch, I decided to add a incremental lottery number and the error stop. (I'm assuming lottery number has to be unique within a weight class?)

It would be good if we got some better exception messages coming from the API, specially with data this bad. :)

**To Reproduce**

500 Server Error: Internal Server Error for url: https://api.lifter.shivan.xyz/v1/competitions/V21v3pd/lifts
```
{
  "lottery_number": 0,
  "athlete_id": "nbnqe8w",
  "competition_id": "V21v3pd",
  "bodyweight": 60.4,
  "weight_category": "M62",
  "team": "WC",
  "session_number": 0.0,
  "snatch_first": "LIFT",
  "snatch_first_weight": 85.0,
  "snatch_second": "NOLIFT",
  "snatch_second_weight": 90.0,
  "snatch_third": "NOLIFT",
  "snatch_third_weight": 92.0,
  "cnj_first": "LIFT",
  "cnj_first_weight": 110.0,
  "cnj_second": "NOLIFT",
  "cnj_second_weight": 116.0,
  "cnj_third": "NOLIFT",
  "cnj_third_weight": 116.0
}
```

**Comment by shivan-s** [comment]
Hey Diogo, you are right.

There is a unique constraints:

```
    class Meta:
        ordering = ["weight_category", "lottery_number"]
        constraints = [
            models.UniqueConstraint(
                fields=["competition", "lottery_number", "weight_category"],
                name="session_lottery_unique_combination",
            ),
            models.UniqueConstraint(
                fields=["competition", "athlete"],
                name="competition_athlete_unique_combination",
            ),
        ]
```

I agree with you about the error messages. I'll need to find out how to return the appropriate error message.

I think what happens is that Django sees a unique constraint is violated and just throws an exception of the backend, and when that happens a 500 is returned to the client, which isn't too useful.

I can also add you to Sentry (unsure about teams, but we can try) so you can see these error messages.

https://sentry.io/organizations/shivan-sivakumaran/issues/3477308157/?project=6609493&query=is%3Aunresolved

**Comment by shivan-s** [comment]
I didn't do a pull request for this @ditorelo (I forgot and this is being merged straight onto the main branch lol)

**Comment by shivan-s** [comment]
@ditorelo just to add. You should get back a bad error with an error message as to why for unique constraints like this.
